name: Update meals

on:
  # schedule:
  #   - cron: '0 15 * * 0'

  workflow_dispatch:

jobs:
  update-meals:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Update meals data
        run: node scripts/updateMeals.js

      - name: Commit & push changes
        run: |
          if git status --porcelain | grep .; then
            git config user.name "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"
            git add data/meals.json
            git commit -m "chore: update meals data"
            git push
          else
            echo "No changes detected"
          fi